### ISSUE TITLE
Documentation doesn't match repo?

### ISSUE THREAD

**Issue by Efreak** [baxterthehacker/public-repo#4]
1. According to [docs](https://developer.github.com/v3/activity/events/types/#releaseevent), there is a release. The repo does not have one. Going to the html_url gets me an error.
2. Several fields mentioned in the documentation are missing or incorrectly names:
   1. [issue event](https://developer.github.com/v3/activity/events/types/#issuesevent)
      1. shows a payload.label item, but there is no such item in the example. 
      2. payload.assignee is actually payload.issue.assignee in the example.
   2. [Push](https://developer.github.com/v3/activity/events/types/#pushevent) is missing the size, 
3. It would be nice if there was a simpler object available. For example, _sender_, _author_, _repository_, etc are always the same type of object; you can remove these entirely and just replace [ReleaseEvent](https://developer.github.com/v3/activity/events/types/#releaseevent)'s example with the following:
   
   ``` javascript
   {
   "action": "published",
   "release": {
     "url": "https://api.github.com/repos/baxterthehacker/public-repo/releases/1261438",
     "assets_url": "https://api.github.com/repos/baxterthehacker/public-repo/releases/1261438/assets",
     "upload_url": "https://uploads.github.com/repos/baxterthehacker/public-repo/releases/1261438/assets{?name}",
     "html_url": "https://github.com/baxterthehacker/public-repo/releases/tag/0.0.1",
     "id": 1261438,
     "tag_name": "0.0.1",
     "target_commitish": "master",
     "name": null,
     "draft": false,
     "author": Object, //replaced with a generic
     "prerelease": false,
     "created_at": "2015-05-05T23:40:12Z",
     "published_at": "2015-05-05T23:40:38Z",
     "assets": [
   
     ],
     "tarball_url": "https://api.github.com/repos/baxterthehacker/public-repo/tarball/0.0.1",
     "zipball_url": "https://api.github.com/repos/baxterthehacker/public-repo/zipball/0.0.1",
     "body": null
   },
   "repository": Object, //replaced with generic
   "sender": Object //replaced with generic
   }
   ```
   
   I realize that the documentation is just markdown, but it would be even better if there was a json code format that allowed collapsing and expanding objects. Something like this [open source](http://quickjsonformatter.codeplex.com/license) [JsonFormatter](http://www.bodurov.com/JsonFormatter/) or like [CodeMirror](https://github.com/codemirror/codemirror)
4. I would expect to see unavailable endpoints either not listed or in their own section at the bottom of the page, rather than in between endpoints that are still in use.
5. It would be nice if there was an endpoint _tester_ that we could use to see exactly what the response would be for specific actions. I don't currently know whether the example code or the documentation is correct when they conflict, and I don't yet have anything to test with.

**Comment by kdaigle** [comment]
@Efreak would you mind contacting [support](https://github.com/contact) for this? We'd love to help you there as this is just a stub repository. :grinning: Thanks!
